### ISSUE TITLE
Problems with Clustered nats and goRouter startup

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/yagnats#8]
We are using clustered nats with gorouter.  Our go router nats config looks like:

```
nats:
  - host: 10.10.10.10
    port: 4222
    user: user
    pass: "pass"
  - host: 10.10.10.11 
    port: 4222
    user: user
    pass: "pass"
```

If nats vm 10.10.10.11 is down then gorouter never starts.  This is caused by 2 things:
- When a nats VM is shutdown it takes a long time for a nats connection attempt to timeout.
- yagnats "randomly" picks a member of the cluster to use.  (see https://github.com/cloudfoundry/yagnats/blob/master/connection.go#L89).  However, because rand is not Seeded rand.Intn(2).  Consistently returns:
  1,1,1,1,1,0  Everytime the process starts.

This means that yagnats will try to connect to index 1 five times before trying index 0.  If it takes a long time for index 1 to fail then monit will restart gorouter and the cycle of choosing index 1 starts over.

To fix this I propose the following changes:
- Use net.DialTimeout with a timeout of something like 5 seconds???
- Seed math.rand with something like "time" so the order is not so predictable.

I'd be happy to submit a PR for this if my proposed solution looks good.
